### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samuelcregan17**
While trying to use this library in a Gradle project, I was running into the error "Unable to access CRS file: proj4/nad/epsg". I noticed the note for Maven projects to add the epsg dependency, so tried adding it to my Gradle dependencies and it solved the problem.

### CODE REVIEW

**Comment by pomadchin** [comment]
Hi @samuelcregan17,  could you sign [ECA](https://www.eclipse.org/legal/ECA.php) to make Eclipse ECA Validator happy?

Also wondering, could you refactor it to make it looks similar to the maven description? https://github.com/locationtech/proj4j?tab=readme-ov-file#proj4j-epsg

**Comment by samuelcregan17** [comment]
@pomadchin I signed the ECA and made those changes. Is this what you had in mind?

**Comment by pomadchin** [comment]
@samuelcregan17 thanks!

**Review by pomadchin — APPROVED** [review]
🎉 with your first contribution!

**Pull request merged**
