### PR TITLE
Extend README, add basic user guide

### PR DESCRIPTION
**Pull request by sebkur**
Signed-off-by: Sebastian Kürten <sebastian@topobyte.de>

### CODE REVIEW

**Comment by sebkur** [comment]
See a rendered version of the changes here: https://github.com/sebkur/proj4j/tree/improve-docs

**Comment by pomadchin** [comment]
Hey @sebkur! Thanks for a cool PR. How do you feel about putting that quick user guide directly into the README.md?

**Comment by sebkur** [comment]
My primary intention was to add an example as it took me a few minutes to get some working code and would have liked to see some examples that let me dive right in.

In the process of doing that, I compared the current README.md to the one from JTS and figured there are a bunch of other things that should probably be there and added some of the obvious things:
* state connection to LocationTech
* linkify contribution guide
* add user guide
* in the user guide:
    * add explanation how to use on Maven
    * add explanation how to use on Gradle
    * add examples

**Comment by sebkur** [comment]
> Hey @sebkur! Thanks for a cool PR. How do you feel about putting that quick user guide directly into the README.md?

yeah, seems like a good idea. Unless the main README gets too long, I think it would fit there quite well

**Comment by pomadchin** [comment]
@sebkur somewhere under the  `Building, Testing and installing locally` section probably?

**Comment by pomadchin** [comment]
Thanks for doing that hard work! Everyone always forgets about docs, that's a big problem.

**Comment by sebkur** [comment]
Ok, pushed a new version

**Review by pomadchin — APPROVED** [review]
Thanks! That's a wonderful addition. And this is also your first contribution into this project! 🎉 🎉 🎉

**Comment by sebkur** [comment]
thanks for the quick response!

**Pull request merged**
