### PR TITLE
Move nad resources to epsg submodule

### PR DESCRIPTION
**Pull request by bchapuis**

### CODE REVIEW

**Comment by pomadchin** [comment]
🤦 I'll double check files contents with the pre 1.2.x version. Also there should be no dependency between core and epsg I think, or it should be a provided one.

**Comment by bchapuis** [comment]
Good catch, I went too fast when reporting my changes in the fork...

**Comment by pomadchin** [comment]
Could you also sign [ECA](https://www.eclipse.org/legal/ECA.php) to make Eclipse ECA Validator happy?

This is also not really a code change so I think it is _fine_ to merge it as is.

**Comment by pomadchin** [comment]
Thank you for helping with it! I definitely needed a second pair of eyes. :+1:

**Comment by bchapuis** [comment]
I signed the Eclipse Contributor Agreement, but there is still a problem with the "Eclipse Foundation Specification Project". Any idea where this check comes from?

**Comment by bchapuis** [comment]
Quick note on the −16,166 lines: many resources files were duplicated in the java and test directory.

**Comment by pomadchin** [comment]
@bchapuis the actual error is `Could not validate the users ECA sign-off status. Please ensure that the e-mail address of all contributing accounts match a valid Eclipse Foundation account with a valid ECA.` but from the other hand I can find you with a signed ECA there; hmmm

**Comment by bchapuis** [comment]
Sorry, I have not been able to sort this out. I don't want to slow you down so feel free to ignore this PR. For future contribution, is there some administrative contact at the eclipse foundation that can help sorting this kind of issue?

**Comment by pomadchin** [comment]
Hey @bchapuis I think usually hit the repo maintainers, but if you want to go full hardcore its usually EMO (emo (at) eclipse.org), more contacts can be found here https://www.eclipse.org/org/foundation/contact.php

**Comment by pomadchin** [comment]
Thanks for you contribution! ECA is green as well.

**Pull request merged**
