### PR TITLE
Add geo projection in Registry

### PR DESCRIPTION
**Pull request by Yaqiang**
Add geo projection in Registry, so Proj4Parser can get GeostationarySatelliteProjection with the code: projection = registry.getProjection(s);

### CODE REVIEW

**Comment by pomadchin** [comment]
Hey @Yaqiang can you create a cleaner PR? Just a new one with a single singed commit?

**Comment by pomadchin** [comment]
hey @Yaqiang, if it's a fresh commit it is enough just to do `git commit -s -m "commit message"` actually flag `-s` adds a footer that is required.

**Comment by pomadchin** [comment]
Can you create a new PR that has a single clean commit?

**Comment by Yaqiang** [comment]
I tried your recommond:

D:\MyProgram\java\proj4j>git commit -s -m "add geo projection in registry"
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

It seems nothing happen. Maybe you can close this pull requests, and revise the code yourself. The purpose is problem solving. Thanks!

**Comment by pomadchin** [comment]
Hey @Yaqiang try the following: 

```bash
# save your current changes in case you loose everything during your next steps
# git supports branches
git checkout -b tmp
# lets add a remote (the current) repo as an upstream repo
git remote add upstream git@github.com:locationtech/proj4j.git
# fetch it
git fetch upstream
# rebase master on top of it
git checkout -f master && git reset --hard f900cff && git rebase upstream/master && git push origin -f master
# create a new feature branch with the stuff you want to contribute
git checkout -b feature/add-into-registry
# add your code changes and after that do 
git add . && git commit -s -m "add geo projection in registry" && git push origin feature/add-into-registry
```

After that try to create a new PR.

**Comment by pomadchin** [comment]
I guess it should be a commit with the only change introduced into `Registry.java`:

```java
register("geos", GeostationarySatelliteProjection.class, "Geostationary Satellite");
```

**Comment by pomadchin** [comment]
@Yaqiang check it out https://github.com/locationtech/proj4j/pull/27

**Comment by Yaqiang** [comment]
@pomadchin You are right with the only change line code. So I will close this pull request.

**Pull request closed without merging**
