### PR TITLE
return the default unit when the unit is not set

### PR DESCRIPTION
**Pull request by bosborn**

### CODE REVIEW

**Comment by pomadchin** [comment]
Hey @bosborn can you sign your commit? 

`git commit --amend -s`

**Comment by bosborn** [comment]
Is that better?

**Comment by pomadchin** [comment]
@bosborn yep, it looks like you need to sign [ECA](https://www.eclipse.org/legal/ECA.php). If that's not hard, can you do it?

**Comment by bosborn** [comment]
Signed it.  I don't see a way to make "Eclipse Foundation Specification Project" happy.  Is there some other place that needs signed?

Screen Shot 2019-04-19 at 7 13 16 AM

**Comment by pomadchin** [comment]
@bosborn mb you’ve signed your commit with a wrong email?

**Comment by bosborn** [comment]
Fixed in #28

**Pull request closed without merging**
