### PR TITLE
Extended Transverse Mercator

### PR DESCRIPTION
**Pull request by halset**
Added support for Extended Transverse Mercator. Ported from proj.4

### CODE REVIEW

**Comment by lossyrob** [comment]
This would need sign off footers (as described here https://github.com/locationtech/geotrellis/blob/master/docs/CONTRIBUTING.rst#pull-requests), and for you to sign a Eclipse ECA.

Looks like the Eclipse hooks are not in place, we'll have to file a ticket for getting that set up for this repo

**Comment by halset** [comment]
I have signed a Eclipse ECA now. Should I create a new pull-request with signed commits or can this pull-request be signed afterwards?

**Comment by lossyrob** [comment]
You can either start a new PR with new commits (I'd recommend using `git cherry-pick -s xxxxxx` on a new branch to cherry pick commits), or rebase this branch to have signed commits and force push to update this PR.

**Comment by halset** [comment]
Thanks! #6 is a signed version of this.

**Pull request closed without merging**
